# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# 1. Import Suitable Libraries
import pandas as pd
import numpy as np

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning Libraries
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score
)

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

#2. Load Dataset
df = pd.read_csv("student_data.csv")
# Display first 5 rows
print("First 5 Rows")
print(df.head())

#3. Data Exploration

# Shape of dataset
print("Dataset Shape:")
print(df.shape)

# Dataset information
print("Dataset Information:")
print(df.info())

# Summary statistics
print("Summary Statistics:")
print(df.describe())

# Check missing values
print("Missing Values:")
print(df.isnull().sum())

# Check duplicates
print("Duplicate Rows:")
print(df.duplicated().sum())

# 4. Exploratory Data Analysis (EDA)
# Distribution of Final Grades
plt.figure(figsize=(8,5))
sns.histplot(df["G3"], bins=10, kde=True)
plt.title("Distribution of Final Grades (G3)")
plt.xlabel("Final Grade")
plt.ylabel("Count")
plt.show()

# Boxplot for Outliers
plt.figure(figsize=(8,5))
sns.boxplot(x=df["absences"])
plt.title("Boxplot of Absences")
plt.show()

# Gender Distribution
plt.figure(figsize=(6,4))
sns.countplot(x=df["sex"], data=df)
plt.title("Gender Distribution")
plt.show()

# Select numerical columns only
numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# 5. Create Target Variable
# Pass = 1 , Fail = 0

df["Result"] = df["G3"].apply(lambda x: 1 if x >= 10 else 0)

print("Target Variable Created Successfully")
print(df["Result"].value_counts())

# 6. Encode Categorical Variables
label_encoder = LabelEncoder()

# Convert categorical columns into numbers
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = label_encoder.fit_transform(df[column])

# 7. Feature Selection
# Features
X = df.drop(["G3", "Result"], axis=1)
# Target
y = df["Result"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

# 8. Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

# 9. Build Classification Model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
model.fit(X_train, y_train)

# 10. Predictions
y_pred = model.predict(X_test)

# 11. Model Evaluation
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:")
print(accuracy)

# F1 Score
f1 = f1_score(y_test, y_pred)

print("F1 Score:")
print(f1)

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# 12. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Plot confusion matrix
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# 13. Feature Importance
importance = model.feature_importances_

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print("Feature Importance:")
print(feature_importance)

# Plot feature importance
plt.figure(figsize=(10,6))
sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_importance
)

plt.title("Feature Importance")
plt.show()

# 14. Interpretation
print("Interpretation:")
print("The Random Forest Classifier was used to predict whether")
print("a student will pass or fail based on academic and social factors.")
print("The model achieved good accuracy and F1-score,")
print("showing that the selected features are useful for prediction.")

# 15. Conclusion
print("Conclusion:")
print("This project successfully developed a classification model")
print("to predict student academic performance.")
print("Exploratory Data Analysis, preprocessing,")
print("and machine learning techniques were applied effectively.")